production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: jdogs
  username: root
  password: im1coolguy

development:
  adapter: mysql2
  pool: 5
  timeout: 5000
  database: jdogs
  username: root
  password: im1coolguy

test:
  adapter: mysql2
  pool: 5
  timeout: 5000
  database: jdogs_test
  username: root
  password: im1coolguy
